######################################################################
# Automatically generated by qmake (3.0) sam. mai 10 10:13:14 2014
######################################################################

TEMPLATE = app
QT += widgets webkitwidgets gui
TARGET = webbrowser
INCLUDEPATH += .
QTPLUGIN += qjpeg

# Input
HEADERS += Window.hpp 
SOURCES += main.cpp Window.cpp 
